pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { 
                    image 'maven:3.9.6-eclipse-temurin-21'
                    label 'docker'
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker { 
                    image 'node:20-alpine'
                    label 'docker'
                }
            }
            steps {
                sh 'node --version'
                sh 'sleep 15' // Keeps the container active so you can catch it
            }
        }
    }
}
